name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: "5.3.x"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.nuGetVersion }}
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Pack
        if: github.ref == 'refs/heads/main'
        run: dotnet pack --no-restore --verbosity normal --output ./nupkg /p:Version=${{ steps.gitversion.outputs.nuGetVersion }}
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push ./nupkg/*.nupkg --skip-duplicate --no-symbols true --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: Commit tagger
        if: github.ref == 'refs/heads/main'
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.gitversion.outputs.semVer }}
